mysql:
  host: 127.0.0.1
  port: 3306
  config: ""
  db: db
  user: root
  password: 2864//
  log_level: dev
  parse_time: "true"
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
site_info:
  created_at: "2023-02-15"
  bei_an: 湘ICP备2021010654号-3
  title: 枫枫知道
  version: 1.3.5
  email: 2862946703@qq.com
  name: 中学课堂
  job: 后端开发
  addr: 广东深圳
  slogan: 中学课堂
  slogan_en: FENGFENGZHIDAO
  web: http://www.fengfengzhidao.com/
  bilibili_url: https://space.bilibili.com/359151217
  gitee_url: https://gitee.com/fengfengzhidao
  github_url: https://github.com/fengfengzhidao/
email:
  host: smtp.qq.com
  port: 465
  user: 2862946703@qq.com
  password: 1234
  default_from_email: 枫枫知道
  use_ssl: true
  user_tls: false
jwy:
  secret: xxxx
  expires: 20
  issuer: "1234"
node:
  nid: "2"
  nodename: 澳门
  country: 中国
  bandwidth: 120M
  tel: "17671054954"
  addr: ribrn
  token: ""
  ip: 127.0.0.1
  link: http://127.0.0.1:8080/api/settings
  nodetype: "0"
redis:
  ip: 127.0.0.1
  port: 6379
  password: "12345"
  pool_size: 100
